import os
from os import environ
from info import ( is_enabled, id_pattern, SESSION, API_ID, API_HASH, BOT_TOKEN, ADMINS, CHANNELS, CACHE_TIME, 
    DATABASE_NAME, DATABASE_URI, COLLECTION_NAME, AUTH_USERS, AUTH_CHANNEL, AUTH_GROUPS, LOG_CHANNEL, SUPPORT_CHAT, 
    P_TTI_SHOW_OFF, IMDB, SINGLE_BUTTON, TEMPLATE, IMDB_TEMPLATE, BATCH_FILE_CAPTION, PROTECT_CONTENT, BOT_START_TIME,
    FILE_STORE_CHANNEL, PUBLIC_FILE_STORE, MELCOW_NEW_USERS, WLCM, USE_CAPTION_FILTER, SPELL_CHECK_REPLY, SESSION, LOG_STR,
    LONG_IMDB_DESCRIPTION, MAX_LIST_ELM, GET_FILECHANNEL, CHANNEL_ON, REQUEST_MODE, CLEAN )
from .Script import script

SESSION = SESSION
LOG_STR = LOG_STR
API_ID = API_ID
API_HASH = API_HASH
BOT_TOKEN = BOT_TOKEN
DATABASE_NAME = DATABASE_NAME
DATABASE_URI = DATABASE_URI
CHANNELS = CHANNELS
ADMINS = ADMINS
TEMPLATE = TEMPLATE
IMDB_TEMPLATE = IMDB_TEMPLATE
SINGLE_BUTTON = SINGLE_BUTTON
AUTH_CHANNEL = AUTH_CHANNEL
AUTH_USERS = AUTH_USERS
AUTH_GROUPS = AUTH_GROUPS
LOG_CHANNEL = LOG_CHANNEL
BATCH_FILE_CAPTION = BATCH_FILE_CAPTION
PROTECT_CONTENT = PROTECT_CONTENT
SUPPORT_CHAT = SUPPORT_CHAT
FILE_STORE_CHANNEL = FILE_STORE_CHANNEL
PUBLIC_FILE_STORE = PUBLIC_FILE_STORE
CACHE_TIME = CACHE_TIME
MELCOW_NEW_USERS = MELCOW_NEW_USERS
IMDB = IMDB
WLCM = WLCM
LONG_IMDB_DESCRIPTION = LONG_IMDB_DESCRIPTION
MAX_LIST_ELM = MAX_LIST_ELM
USE_CAPTION_FILTER = USE_CAPTION_FILTER
SPELL_CHECK_REPLY = SPELL_CHECK_REPLY
P_TTI_SHOW_OFF = P_TTI_SHOW_OFF
GET_FILECHANNEL = int(GET_FILECHANNEL)
CHANNEL_ON = CHANNEL_ON
REQUEST_MODE = REQUEST_MODE
CLEAN = CLEAN
CUSTOM_FILE_CAPTION = environ.get("CUSTOM_FILE_CAPTION", script.FILECAP_TXT)
COMMANDS = ["pmautofilter", "connections", "delete", "del", "deleteall", "settings", "setskip", "copy", "set_fcap", "add", "set_template", "set_welcome", "leave", "disable", "enable", "stats", "invite", "ban", "unban", "users", "chats", "id", "info", "imdb", "search", "format"]

class temp(object):
    BANNED_USERS = []
    BANNED_CHATS = []
    ME = None
    CURRENT=int(os.environ.get("SKIP", 2))
    CANCEL = False
    MELCOW = {}
    U_NAME = None
    B_NAME = None
    SETTINGS = {}
    PMAF_OFF = []
